apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
  labels:
    type: local
spec:
  storageClassName: sc-elasticsearch
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/data/elasticsearch"