apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  labels:
    type: local
spec:
  storageClassName: sc-grafana
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/data/grafana"