apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logstash
  labels:
    type: local
spec:
  storageClassName: sc-logstash
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/data/logstash"