apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-server
  labels:
    type: local
spec:
  storageClassName: sc-prometheus-server
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/data/prometheus/server"
