apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alert-manager
  labels:
    type: local
spec:
  storageClassName: sc-prometheus-alert-manager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/prometheus/alert-manager"